CREATE TABLE `WEBPORTAL_CLOUDVM_FLOATING_IP` (
	`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	`REGION` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`FLOATING_IP_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`SERVER_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`TENANT_ID` bigint(20) DEFAULT NULL,
	`FLOATING_NETWORK_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`FLOATING_IP_ADDRESS` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`BAND_WIDTH` smallint(4) DEFAULT NULL,
	`NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`STATUS` tinyint(4) DEFAULT NULL,
	`DELETED` tinyint(4) DEFAULT NULL,
	`CREATE_TIME` datetime DEFAULT NULL,
	`UPDATE_TIME` datetime DEFAULT NULL,
	`CREATE_USER` bigint(20) unsigned DEFAULT NULL,
	`UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8;
