CREATE TABLE `WEBPORTAL_CLOUDVM_SUBNET_OPTION` (
	`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	`CIDR` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`GATEWAY_IP` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`DELETED` tinyint(4) DEFAULT NULL,
	`CREATE_TIME` datetime DEFAULT NULL,
	`UPDATE_TIME` datetime DEFAULT NULL,
	`CREATE_USER` bigint(20) unsigned DEFAULT NULL,
	`UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8;

insert into WEBPORTAL_CLOUDVM_SUBNET_OPTION(CIDR,GATEWAY_IP,CREATE_TIME) VALUES('192.168.0.0/24','192.168.0.1',now());
insert into WEBPORTAL_CLOUDVM_SUBNET_OPTION(CIDR,GATEWAY_IP,CREATE_TIME) VALUES('192.168.1.0/24','192.168.1.1',now());
insert into WEBPORTAL_CLOUDVM_SUBNET_OPTION(CIDR,GATEWAY_IP,CREATE_TIME) VALUES('192.168.2.0/24','192.168.2.1',now());
insert into WEBPORTAL_CLOUDVM_SUBNET_OPTION(CIDR,GATEWAY_IP,CREATE_TIME) VALUES('192.168.3.0/24','192.168.3.1',now());
insert into WEBPORTAL_CLOUDVM_SUBNET_OPTION(CIDR,GATEWAY_IP,CREATE_TIME) VALUES('172.16.0.0/16','172.16.0.1',now());
