CREATE TABLE `WEBPORTAL_MONITOR_OSS_REQFREQ` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `DETAIL_NAME` varchar(50) DEFAULT NULL,
  `DETAIL_VALUE` float(30,3) DEFAULT NULL,
  `MONITOR_DATE` datetime DEFAULT NULL,
  `IP` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NAME_IP_DATE` (`DETAIL_NAME`(10),`IP`(13),`MONITOR_DATE`)
) ENGINE=InnoDB AUTO_INCREMENT=2616 DEFAULT CHARSET=utf8;

CREATE TABLE `WEBPORTAL_MONITOR_OSS_THROUGHPUT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `DETAIL_NAME` varchar(50) DEFAULT NULL,
  `DETAIL_VALUE` float(30,3) DEFAULT NULL,
  `MONITOR_DATE` datetime DEFAULT NULL,
  `IP` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `NAME_IP_DATE` (`DETAIL_NAME`(10),`IP`(13),`MONITOR_DATE`)
) ENGINE=InnoDB AUTO_INCREMENT=3536 DEFAULT CHARSET=utf8;

INSERT INTO `WEBPORTAL_INDEX_MONITOR` VALUES (35,'oss.reqfreq',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'WEBPORTAL_MONITOR_OSS_REQFREQ',3,'/swift/manager/usermetric/AUTH_{0}?filter=reqfreq','reqfreq_put,reqfreq_get,reqfreq_delete,reqfreq_post,reqfreq_head'),(36,'oss.throughput',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'WEBPORTAL_MONITOR_OSS_THROUGHPUT',3,'/swift/manager/usermetric/AUTH_{0}?filter=throughput','throughput_put,throughput_get,throughput_delete,throughput_post,throughput_head');

alter table WEBPORTAL_GCECONTAINER ADD COLUMN `LOG_BIND_HOST_PORT` varchar(10) DEFAULT NULL;