alter table WEBPORTAL_SLB_BACKEND_SERVER add column  SLB_CONFIG_ID bigint unsigned

insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (6, 'taskMclusterCreateService', null, 'taskMclusterCreateService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (7, 'taskMclusterCheckStatusService', null, 'taskMclusterCheckStatusService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (8, 'taskMclusterInitZookeeperService', null, 'taskMclusterInitZookeeperService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (9, 'taskMclusterInitAdminUserAndPwdService', null, 'taskMclusterInitAdminUserAndPwdService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (10, 'taskMclusterPostInfoService', null, 'taskMclusterPostInfoService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (11, 'taskMclusterInitService', null, 'taskMclusterInitService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (12, 'taskDbCreateService', null, 'taskDbCreateService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (13, 'taskDbUserCreateService', null, 'taskDbUserCreateService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (14, 'taskContainerSyncService', null, 'taskContainerSyncService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (15, 'taskContainerPostInfoService', null, 'taskContainerPostInfoService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (16, 'taskContainerSync2Service', null, 'taskContainerSync2Service', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (17, 'taskContainerPostInfo2Service', null, 'taskContainerPostInfo2Service', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (18, 'taskMclusterStartService', null, 'taskMclusterStartService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (19, 'taskContainerCheckStatusService', null, 'taskContainerCheckStatusService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (20, 'taskMclusterStartGlb3306Service', null, 'taskMclusterStartGlb3306Service', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (21, 'taskMclusterStartGlb8888Service', null, 'taskMclusterStartGlb8888Service', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (22, 'taskFixedPushService', null, 'taskFixedPushService', null, 1, null, null, null, null, null, null);
insert into WEBPORTAL_TEMPLATE_TASK_DETAIL (ID, NAME, DESCN, BEANNAME, PARAMS, RETRY, VERSION, DELETED, CREATE_TIME, UPDATE_TIME, CREATE_USER, UPDATE_USER) values (23, 'taskZabbixPushService', null, 'taskZabbixPushService', null, 1, null, null, null, null, null, null);
