/*
 * 新增gce容器扩展表，存储gce内外网映射端口
 */
DROP TABLE WEBPORTAL_GCECONTAINER_EXT;
CREATE TABLE `WEBPORTAL_GCECONTAINER_EXT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'container扩展表主键',
  `CONTAINER_ID` bigint(20) DEFAULT NULL COMMENT 'GCE容器ID',
  `BIND_PORT` varchar(10) DEFAULT NULL COMMENT '绑定端口',
  `INNER_PORT` varchar(10) DEFAULT NULL COMMENT '内部端口',
  `DELETED` tinyint(4) DEFAULT NULL COMMENT '是否删除',
  `TYPE` varchar(20) DEFAULT NULL COMMENT '类型',
  `DESCN` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '描述',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` datetime DEFAULT NULL COMMENT '更新时间',
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL COMMENT '创建人ID',
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8 COMMENT='container扩展表'
