/*
 * 新增字典表，一期只存业务类型名称：SLB，OSS等
 */
DROP TABLE WEBPORTAL_DICTIONARY;
CREATE TABLE `WEBPORTAL_DICTIONARY` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '字典表主键',
  `NAME` VARCHAR(100) DEFAULT NULL COMMENT '名称',
  `TYPE` TINYINT(2) DEFAULT NULL COMMENT '类型:0-服务类型',
  `DESCN` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '描述',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `UPDATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '字典表';

/*
 * 新增镜像表
 */
DROP TABLE WEBPORTAL_IMAGE;
CREATE TABLE `WEBPORTAL_IMAGE` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '镜像表主键',
  `NAME` varchar(100) DEFAULT NULL COMMENT '名称',
  `DICTIONARY_ID` VARCHAR(100) DEFAULT NULL COMMENT '业务类型ID，例如：字典表GCE主键',
  `PURPOSE` VARCHAR(100) DEFAULT NULL COMMENT '用途',
  `URL` VARCHAR(500) DEFAULT NULL COMMENT '接口地址',
  `TAG` VARCHAR(100) DEFAULT NULL COMMENT '镜像版本',
  `ISUSED` TINYINT(1) DEFAULT 0 COMMENT '是否使用：1使用，0未使用',
  `DESCN` VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '描述',
  `CREATE_TIME` DATETIME DEFAULT NULL COMMENT '创建时间',
  `UPDATE_TIME` DATETIME DEFAULT NULL COMMENT '更新时间',
  `CREATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '创建人ID',
  `UPDATE_USER` BIGINT(20) UNSIGNED DEFAULT NULL COMMENT '更新人ID',
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '镜像表';

/* 
 * add new field 'MEMERY_SIZE' into WEBPORTAL_GCE
 */
alter table WEBPORTAL_GCE ADD COLUMN MEMORY_SIZE  bigint(20) COMMENT '内存大小';
update WEBPORTAL_GCE SET MEMORY_SIZE='1073741824' WHERE  MEMORY_SIZE IS NULL;