CREATE TABLE `WEBPORTAL_SWIFT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `HCLUSTER_ID` bigint(20) unsigned DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `DESCN` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `STORE_SIZE` bigint(20) DEFAULT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  `VISIBILITY_LEVEL` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;


/*
 * update WEBPORTAL_SLB_BACKEND_SERVER .
 */
ALTER TABLE `paascloud_test`.`WEBPORTAL_SLB_BACKEND_SERVER` 
CHANGE COLUMN `CONTAINER_ID` `GCE_ID` BIGINT(20) UNSIGNED NULL DEFAULT NULL ;