CREATE TABLE `WEBPORTAL_CLOUDVM_SERVER` (
	`ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
	`REGION` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`SERVER_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`FLAVOR_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
	`NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`SERVER_UUID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`TENANT_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`USER_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`UPDATED` datetime DEFAULT NULL,
	`CREATED` datetime DEFAULT NULL,
	`HOST_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`ACCESS_IPV4` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`ACCESS_IPV6` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`IMAGE_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`KEY_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`CONFIG_DRIVE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_STATUS_TASK_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_STATUS_VM_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_STATUS_POWER_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_ATTRIBUTES_INSTANCE_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_ATTRIBUTES_HOST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`EXTENDED_ATTRIBUTES_HYPERVISOR_HOST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`DISK_CONFIG` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`AVAILABILITY_ZONE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
	`DELETED` tinyint(4) DEFAULT NULL,
	`CREATE_TIME` datetime DEFAULT NULL,
	`UPDATE_TIME` datetime DEFAULT NULL,
	`CREATE_USER` bigint(20) unsigned DEFAULT NULL,
	`UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8;



ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `NAME` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `SERVER_UUID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `TENANT_ID` char(32) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `USER_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `UPDATED` datetime DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `CREATED` datetime DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `HOST_ID` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `ACCESS_IPV4` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `ACCESS_IPV6` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `IMAGE_ID` char(36) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `KEY_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `CONFIG_DRIVE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_STATUS_TASK_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_STATUS_VM_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_STATUS_POWER_STATE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_ATTRIBUTES_INSTANCE_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_ATTRIBUTES_HOST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `EXTENDED_ATTRIBUTES_HYPERVISOR_HOST_NAME` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `DISK_CONFIG` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` ADD `AVAILABILITY_ZONE` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;

ALTER TABLE `WEBPORTAL_CLOUDVM_SERVER` MODIFY COLUMN `STATUS` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL;
