-- OpenStack VM vmCount
CREATE TABLE `WEBPORTAL_CLOUDVM_VM_COUNT` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `VM_COUNT` smallint unsigned NOT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8;