CREATE TABLE `WEBPORTAL_TIMING_TASK` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) DEFAULT NULL,
  `UUID` varchar(100) DEFAULT NULL,
  `HTTP_METHOD` varchar(45) DEFAULT NULL COMMENT 'post,get',
  `URL` varchar(200) DEFAULT NULL,
  `TIMING_RULE` varchar(45) DEFAULT NULL,
  `EXEC_TYPE` varchar(45) DEFAULT NULL,
  `DESCN` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  `TYPE` varchar(45) DEFAULT NULL COMMENT 'cron,interval',
  `TIME_POINT` varchar(100) DEFAULT NULL,
  `TIME_INTERVAL` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=266 DEFAULT CHARSET=utf8;