/*start gce*/
CREATE TABLE `WEBPORTAL_GCE` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `GCE_NAME` varchar(20) DEFAULT NULL,
  `HCLUSTER_ID` bigint(20) unsigned DEFAULT NULL,
  `GCECLUSTER_ID` bigint(20) unsigned DEFAULT NULL,
  `GCE_IMAGE_NAME` varchar(100) DEFAULT NULL,
  `IP` varchar(20) DEFAULT NULL,
  `PORT_FORWARD` varchar(100) DEFAULT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `DESCN` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

CREATE TABLE `WEBPORTAL_GCECLUSTER` (
  `ID` bigint(20) unsigned NOT NULL,
  `CLUSTER_NAME` varchar(20) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `SST_PASSWORD` varchar(20) DEFAULT NULL,
  `HCLUSTER_ID` bigint(20) unsigned DEFAULT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '???????????',
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  `ADMIN_USER` varchar(200) DEFAULT NULL,
  `ADMIN_PASSWORD` varchar(200) DEFAULT NULL,
  `TYPE` int(10) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE `WEBPORTAL_GCECONTAINER` (
  `ID` bigint(20) unsigned NOT NULL,
  `CONTAINER_NAME` varchar(20) DEFAULT NULL,
  `MOUNT_DIR` varchar(500) DEFAULT NULL,
  `ZOOKEEPER_ID` varchar(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `IP_ADDR` varchar(15) DEFAULT NULL,
  `GATE_ADDR` varchar(15) DEFAULT NULL,
  `IP_MASK` varchar(15) DEFAULT NULL,
  `TYPE` varchar(15) DEFAULT NULL,
  `DISK_SIZE` int(11) DEFAULT NULL,
  `CORES_NUMBER` int(11) DEFAULT NULL,
  `CPU_SPEED` int(11) DEFAULT NULL,
  `MEMORY_SIZE` int(11) DEFAULT NULL,
  `HOST_ID` bigint(20) unsigned DEFAULT NULL,
  `HOST_IP` varchar(15) DEFAULT NULL,
  `MCLUSTER_ID` bigint(20) unsigned DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  `ZABBIXHOSTS` varchar(20) DEFAULT NULL,
  `SERVICE_TYPE` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
/*end gce*/
/*start task*/
ALTER TABLE `WEBPORTAL_TEMPLATE_TASK` 
ADD COLUMN `NAME` VARCHAR(20) NULL AFTER `ID`,
ADD COLUMN `TASK_TYPE` VARCHAR(20) NULL AFTER `NAME`,
ADD COLUMN `DESCN` VARCHAR(100) NULL AFTER `TASK_TYPE`;

ALTER TABLE `WEBPORTAL_TEMPLATE_TASK_CHAIN` 
ADD COLUMN `RETRY` TINYINT(4) NULL AFTER `EXECUTE_ORDER`;

ALTER TABLE `WEBPORTAL_TEMPLATE_TASK_DETAIL` 
ADD COLUMN `TASK_TYPE` VARCHAR(20) NULL AFTER `BEANNAME`;

ALTER TABLE `WEBPORTAL_TASK_CHAIN` 
ADD COLUMN `RETRY` TINYINT(4) NULL AFTER `EXECUTE_ORDER`;





