/*
 * WEBPORTAL_DB表添加内存大小和存储大小字段
 */
ALTER TABLE WEBPORTAL_DB ADD MEMORY_SIZE BIGINT(20) DEFAULT NULL COMMENT '内存大小';
ALTER TABLE WEBPORTAL_DB ADD STORAGE_SIZE BIGINT(20) DEFAULT NULL COMMENT '存储大小';

alter table WEBPORTAL_BACKUP_RESULT modify column RESULT_DETAIL varchar(500);

