/*
 * WEBPORTAL_DB表添加内存大小和存储大小字段
 */
ALTER TABLE WEBPORTAL_DB ADD MEMORY_SIZE BIGINT(20) DEFAULT NULL COMMENT '内存大小';
ALTER TABLE WEBPORTAL_DB ADD STORAGE_SIZE BIGINT(20) DEFAULT NULL COMMENT '存储大小';

alter table WEBPORTAL_BACKUP_RESULT modify column RESULT_DETAIL varchar(500);

CREATE TABLE `WEBPORTAL_ADMIN_OP_LOG` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `EVENT` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `LOG_TYPE` tinyint DEFAULT NULL,
  `MODULE` varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `DESCRIPTION` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `DELETED` tinyint(4) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` bigint(20) unsigned DEFAULT NULL,
  `UPDATE_USER` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=68 DEFAULT CHARSET=utf8;
